### ISSUE TITLE
Make --help default behavior?

### ISSUE THREAD

**Issue by snoyberg** [fpco/optparse-simple#1]
I've noticed this on a number of projects in the past. Would it be possible to modify the library so that running an executable with no arguments is the same as `--help`? This seems like behavior people would like, e.g. when running `stackage`.

Pinging @chrisdone @DanBurton

**Comment by chrisdone** [comment]
I'd agree. The default optparse output is kind of useless.

**Comment by DanBurton** [comment]
I presume you mean: when the arg parse fails because at least one arg is
mandatory. (If running with no args is a valid invocation, then the help
text should not interfere.)

On Thursday, April 16, 2015, Chris Done notifications@github.com wrote:

> I'd agree. The default optparse output is kind of useless.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fpco/optparse-simple/issues/1#issuecomment-93676527.

## 

-- Dan Burton

**Comment by snoyberg** [comment]
Yes, that's what I meant. I discussed that with Chris, but didn't update the issue to clarify.

**Comment by snoyberg** [comment]
Good catch :)

**Comment by chrisdone** [comment]
Done in https://github.com/fpco/optparse-simple/commit/5f73bcca7aaf610bb35bd8173232aff4598646d1.

**Comment by snoyberg** [comment]
LGTM, please release to Hackage.
