### ISSUE TITLE
Git hash not being shown

### ISSUE THREAD

**Issue by ranjitjhala** [fpco/optparse-simple#13]
Hi @chrisdone -- I was using `optparse-simple` to show the git hash when running LH, but somehow after updating to GHC 8.6.4 this stopped working. I've made a minimal example 
at this repo:

https://github.com/ranjitjhala/hash-test

If you clone and build, you get the following:

```
rjhala@borscht ~/t/hash-test (master)> stack build --fast
...
rjhala@borscht ~/t/hash-test (master)> stack exec -- htest 0
Version 0.1.0.0, Git revision 5bbb05f54b8a2500ee2f32d96d443c5621c778f5 (dirty)
rjhala@borscht ~/t/hash-test (master)> stack exec -- htest 10
Version 0.1.0.0
```

The only difference between the two, is that:

1.  the first one is a modification of your code from `simpleVersion` that uses `$$tGitInfoCwd` (instead of `$$tGitInfoCwdTry`); 
2. the second one directly uses   `simpleVersion` from  `Options.Applicative.Simple`.

Any idea what may be going on?

Thanks!

**Comment by snoyberg** [comment]
Thanks for the report. I think I broke this a few releases ago, and finally pinned it down with your repro. I've released a new version (0.1.1.2) to Hackage.
