### ISSUE TITLE
Add upper bound on optparse-applicative

### ISSUE THREAD

**Issue by adinapoli** [fpco/optparse-simple#14]
At the moment of writing, `optparse-applicative` reached version `0.16.0.0`, which breaks the current version of `optparse-simple`:

```
[1 of 2] Compiling Options.Applicative.Simple ( src/Options/Applicative/Simple.hs, dist/build/Options/Applicative/Simple.o, dist/build/Options/Applicative/Simple.dyn_o )
src/Options/Applicative/Simple.hs:173:23: error:
    • Couldn't match expected type 'ParseError'
                  with actual type 'Maybe String -> ParseError'
    • Probable cause: 'ShowHelpText' is applied to too few arguments
```

Could we have an `optparse-applicative < 0.16.0.0` upper bound for version `0.1.1.2` of this library, even just in the form of a Hackage revision bump, for folks building the library with `cabal`?

Thank you 🙂

**Comment by snoyberg** [comment]
I'll release a new version, but I don't intend to go back and add upper bounds on previous versions. It's a bunch of work I won't volunteer for.

**Comment by adinapoli** [comment]
Thanks Michael!

**Comment by snoyberg** [comment]
No problem, thanks for the heads-up
