### ISSUE TITLE
infoOption flags don't work

### ISSUE THREAD

**Issue by DanBurton** [fpco/optparse-simple#2]
Take, for example, the built in `--version` flag.

```
$ mkdir simple-test && cd simple-test
$ stackage sandbox upgrade lts-2.4
$ cabal install optparse-simple
$ cat > Main.hs <<- EOF
import Options.Applicative.Simple
main = do
  ((), ()) <- simpleOptions "version" "header" "desc" (pure ()) empty
  return ()
EOF
$ cabal exec ghc Main
$ ./Main --version
[shows help instead]
```

Such flags are supposed to halt the program with their own output.

**Comment by chrisdone** [comment]
Ah, I missed a check in 5f73bcca7aaf610bb35bd8173232aff4598646d1 to see that `getArgs` is `[]`.

**Comment by DanBurton** [comment]
Fixed it. I also made a call to `handleParseResult` in the other branch, since presumably this does important IO stuff like autocompletion.

**Comment by chrisdone** [comment]
Sweet.

**Comment by snoyberg** [comment]
Can this issue be closed?
